Repository cedarjs/cedar, pull requests merged in 2025-07, with the labels that each got.

#168 chore(tests): Await rejects.toThrowErrorMatchingInlineSnapshot
  packages/cli-helpers/src/lib/__tests__/version.test.ts
  packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.ts
Labels: release:chore

#167 chore(deps): Bump `@joshwooding/vite-plugin-react-docgen-typescript` to v0.6.1
  packages/storybook/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#169 chore(storybook): tsconfig module and moduleResolution nodenext
  packages/storybook/src/index.ts
  packages/storybook/src/mocks/MockProviders.tsx
  packages/storybook/src/mocks/StorybookProvider.tsx
  packages/storybook/src/plugins/react-docgen.ts
  packages/storybook/src/preset.ts
  packages/storybook/src/preview.tsx
  packages/storybook/src/types.ts
  packages/storybook/tsconfig.json
Labels: release:chore

#174 chore(tests): Flush promises before running test
  packages/cli/src/commands/setup/middleware/ogImage/__codemod_tests__/vitePlugin.ts
  packages/cli/src/testUtils/matchTransformSnapshot.ts
Labels: release:chore

#175 chore(vite): Track performance in buildWeb test
  packages/vite/src/build/__tests__/buildWeb.test.ts
Labels: release:chore

#173 chore(deps): Bump pbkdf2 to 3.1.3
  yarn.lock
Labels: changesets-ok, release:dependency

#185 chore(e2e): Break job e2e script up into smaller functions
  tasks/e2e-background-jobs/run.mts
Labels: release:chore

#189 feat(api-server): lambdaLoader: add discoverFunctionsGlob option
  .changesets/189.md
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/__tests__/lambdaLoader.test.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/createServerHelpers.ts
  packages/api-server/src/plugins/api.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/internal/src/files.ts
Labels: release:feature

#190 fix(api-server): lambdaLoader: improve handler import logic
  .changesets/190.md
  packages/api-server/src/plugins/lambdaLoader.ts
Labels: release:fix

#191 feat(cli): upgrade command: Link to Discord instead of forums
  packages/cli/src/commands/upgrade.js
Labels: release:feature, changesets-ok

#194 fix(cli): jobs: Fix cron jsdocs
  packages/jobs/src/types.ts
Labels: release:fix, changesets-ok

#195 feat(cli): cedarjs and cj bins
  packages/api/package.json
  packages/api/src/bins/cedarjs.ts
  packages/cli/package.json
  packages/core/src/bins/cedarjs.ts
  packages/web/package.json
  packages/web/src/bins/cedarjs.ts
  yarn.lock
Labels: release:feature, changesets-ok

#196 chore(deps): Bump zx to 8.7.0
  package.json
  packages/create-cedar-rsc-app/package.json
  packages/create-cedar-rsc-app/yarn.lock
  packages/framework-tools/package.json
  tasks/e2e-background-jobs/run.mts
  yarn.lock
Labels: changesets-ok, release:dependency

#199 fix(core): Add missing bin fields to core/package.json
  packages/core/package.json
  yarn.lock
Labels: changesets-ok

#202 feat(vite): named cedar export from `@cedarjs/vite`
  .eslintrc.js
  README.md
  __fixtures__/fragment-test-project/web/vite.config.ts
  __fixtures__/rsc-caching/web/vite.config.ts
  __fixtures__/test-project-rsa/web/vite.config.ts
  __fixtures__/test-project-rsc-kitchen-sink/web/vite.config.ts
  __fixtures__/test-project/web/vite.config.ts
  packages/cli/src/lib/exec.js
  packages/create-cedar-app/templates/js/web/vite.config.js
  packages/create-cedar-app/templates/ts/web/vite.config.ts
  packages/vite/package.json
  packages/vite/src/index.ts
  packages/vite/src/plugins/__tests__/remove-from-bundle.test.ts
  packages/vite/src/plugins/__tests__/swap-apollo-provider.test.ts
  packages/vite/src/plugins/index.ts
  packages/vite/src/plugins/vite-plugin-cedar-cell.ts
  packages/vite/src/plugins/vite-plugin-cedar-entry-injection.ts
  packages/vite/src/plugins/vite-plugin-cedar-html-env.ts
  packages/vite/src/plugins/vite-plugin-cedar-node-polyfills.ts
  packages/vite/src/plugins/vite-plugin-cedar-remove-from-bundle.ts
  packages/vite/src/plugins/vite-plugin-jsx-loader.ts
  packages/vite/src/plugins/vite-plugin-merged-config.ts
  packages/vite/src/plugins/vite-plugin-remove-from-bundle.ts
  packages/vite/src/plugins/vite-plugin-swap-apollo-provider.ts
Labels: changesets-ok

#207 fix(api): Fix SupportedVerifierTypes import
  packages/api/src/webhooks/index.ts
Labels: changesets-ok

#208 fix(api): Fix webhook exports
  packages/api/src/webhooks/index.ts
  packages/api/src/webhooks/webhooks.test.ts
  packages/api/src/webhooks/webhooks.type.test.ts
Labels: changesets-ok

#203 chore(jobs): Only use zx, not tree-kill
  package.json
  packages/create-cedar-rsc-app/package.json
  packages/create-cedar-rsc-app/yarn.lock
  packages/framework-tools/package.json
  tasks/e2e-background-jobs/run.mts
  yarn.lock
Labels: changesets-ok

#209 docs(server-file): discoverFunctionsGlob
  docs/docs/server-file.md
Labels: changesets-ok

#218 chore(deps): Bump vite to 5.4.19
  packages/ogimage-gen/package.json
  packages/storybook/package.json
  packages/vite/package.json
  yarn.lock
Labels: changesets-ok

#221 chore(deps): Bump Resend from v3.5.0 to v4.6.0
  packages/mailer/handlers/resend/package.json
  packages/mailer/handlers/resend/src/index.ts
  yarn.lock
Labels: changesets-ok, release:dependency

#217 chore(deps): Bump transient dependency undici
  yarn.lock
Labels: changesets-ok

#228 chore(deps): Fix dependency on termi-link
  .github/renovate.json
  packages/auth-providers/dbAuth/setup/package.json
  yarn.lock
Labels: release:chore

#255 fix(dbauth): Revert ESM+CJS PR for dbAuth-web. It broke SSR
  packages/auth-providers/dbAuth/web/.babelrc.js
  packages/auth-providers/dbAuth/web/build.ts
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.middleware.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/webAuthn.test.ts
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
  packages/auth-providers/dbAuth/web/src/index.ts
  packages/auth-providers/dbAuth/web/src/webAuthn.ts
  packages/auth-providers/dbAuth/web/tsconfig.build.json
  packages/auth-providers/dbAuth/web/tsconfig.cjs.json
  packages/auth-providers/dbAuth/web/tsconfig.json
  packages/auth-providers/dbAuth/web/webAuthn/index.js
  packages/auth-providers/dbAuth/web/webAuthn/package.json
  yarn.lock
Labels: release:fix, changesets-ok

#257 feat(dbAuth): Dual mode ESM+CJS dbAuth web package
  packages/auth-providers/dbAuth/web/.babelrc.js
  packages/auth-providers/dbAuth/web/build.ts
  packages/auth-providers/dbAuth/web/package.json
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.middleware.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
  packages/auth-providers/dbAuth/web/src/__tests__/webAuthn.test.ts
  packages/auth-providers/dbAuth/web/src/dbAuth.ts
  packages/auth-providers/dbAuth/web/src/index.ts
  packages/auth-providers/dbAuth/web/tsconfig.build.json
  packages/auth-providers/dbAuth/web/tsconfig.cjs.json
  packages/auth-providers/dbAuth/web/tsconfig.json
  packages/auth-providers/dbAuth/web/webAuthn/index.js
  packages/auth-providers/dbAuth/web/webAuthn/package.json
  packages/vite/src/devFeServer.ts
  packages/vite/src/rsc/rscBuildForSsr.ts
  packages/vite/src/streaming/buildForStreamingServer.ts
  yarn.lock
Labels: changesets-ok

#253 Switch to ansis
  .github/renovate.json
  packages/api-server/package.json
  packages/api-server/src/apiCLIConfigHandler.ts
  packages/api-server/src/bothCLIConfigHandler.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/logFormatter/formatters.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/api-server/src/serverManager.ts
  packages/api-server/src/watch.ts
  packages/cli-helpers/package.json
  packages/cli-helpers/src/lib/colors.ts
  packages/cli-packages/dataMigrate/e2eTest.mjs
  packages/cli-packages/dataMigrate/package.json
  packages/cli-packages/dataMigrate/src/lib/colors.ts
  packages/cli-packages/storybook-vite/package.json
  packages/cli-packages/storybook-vite/src/lib/colors.ts
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/commands/deploy/serverlessHandler.js
  packages/cli/src/commands/experimental/util.js
  packages/cli/src/commands/generate/sdl/sdlHandler.js
  packages/cli/src/lib/colors.js
  packages/cli/src/lib/exit.js
  packages/cli/src/lib/plugin.js
  packages/cli/src/lib/updateCheck.js
  packages/cli/src/testLib/cells.ts
  packages/codemods/src/lib/cells.ts
  packages/codemods/tasks/generateCodemod/generateCodemod.mjs
  packages/create-cedar-app/package.json
  packages/create-cedar-app/tests/__snapshots__/create-cedar-app.out
  packages/create-cedar-app/tests/e2e.test.ts
  packages/create-cedar-rsc-app/package.json
  packages/create-cedar-rsc-app/src/messages.ts
  packages/create-cedar-rsc-app/yarn.lock
  packages/internal/package.json
  packages/internal/src/__tests__/graphqlSchema.test.ts
  packages/internal/src/ast.ts
  packages/internal/src/generate/graphqlSchema.ts
  packages/internal/src/generate/watch.ts
  packages/internal/src/routes.ts
  packages/tui/package.json
  packages/tui/src/index.ts
  packages/web-server/package.json
  packages/web-server/src/webServer.ts
  tasks/changesets/changesets.mts
  tasks/framework-tools/tarsync/lib.mts
  tasks/framework-tools/tarsync/output.mts
  tasks/generateDependencyGraph.mjs
  tasks/k6-test/run-k6-tests.mts
  tasks/k6-test/util/util.mts
  tasks/smoke-tests/smoke-tests.mjs
  tasks/test-project/rebuild-fragments-test-project-fixture.ts
  tasks/test-project/rebuild-test-project-fixture.ts
  tasks/test-project/test-project
  yarn.lock
Labels: release:feature, changesets-ok

#263 feat(gql): Trusted Documents support for CedarJS Mailer
  packages/graphql-server/src/plugins/useRedwoodTrustedDocuments.ts
Labels: release:feature, changesets-ok

#273 fix(prerender): Fix FooPage bug
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/rollup-plugin-cedarjs-routes-auto-loader.test.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-routes-auto-loader.ts
  packages/prerender/src/build-and-import/rollupPlugins/utils.ts
Labels: changesets-ok

#278 fix(prerender): Use built LocationProvider
  packages/prerender/src/build-and-import/buildAndImport.ts
  packages/prerender/src/runPrerender.tsx
Labels: changesets-ok

#293 fix(graphql-server): Point towards correct context import
  packages/graphql-server/src/plugins/useRedwoodGlobalContextSetter.ts
Labels: changesets-ok

#296 fix(api): Fix createRequire for ESM
  packages/api/build.mts
  packages/api/src/index.ts
Labels: changesets-ok

#300 feat(api-server): Dual build as CJS and ESM
  packages/api-server/build.mts
  packages/api-server/dist.test.ts
  packages/api-server/package.json
  packages/api-server/src/__tests__/api.test.ts
  packages/api-server/src/__tests__/buildManager.test.ts
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/__tests__/fastify.test.ts
  packages/api-server/src/__tests__/graphqlPlugin.test.ts
  packages/api-server/src/__tests__/lambdaLoader.test.ts
  packages/api-server/src/__tests__/logFormatter.test.ts
  packages/api-server/src/__tests__/requestHandlers/awsLambdaFastify.test.ts
  packages/api-server/src/__tests__/requestHandlers/utils.test.ts
  packages/api-server/src/apiCLIConfigHandler.ts
  packages/api-server/src/bothCLIConfigHandler.ts
  packages/api-server/src/createServer.ts
  packages/api-server/src/createServerHelpers.ts
  packages/api-server/src/logFormatter/formatters.ts
  packages/api-server/src/logFormatter/index.ts
  packages/api-server/src/plugins/api.ts
  packages/api-server/src/plugins/graphql.ts
  packages/api-server/src/plugins/lambdaLoader.ts
  packages/api-server/src/serverManager.ts
  packages/api-server/src/watch.ts
  packages/api-server/tsconfig.build.json
  packages/api-server/tsconfig.cjs.json
  packages/api-server/tsconfig.json
  yarn.lock
Labels: changesets-ok

#314 fix(context): Don't export function that's only used internally
  packages/context/src/context.ts
Labels: changesets-ok
