Repository cedarjs/cedar, pull requests merged in 2025-06, with the labels that each got.

#103 chore(deps): Upgrade tar-fs to 2.1.3
  yarn.lock
Labels: changesets-ok, release:dependency

#104 chore(deps): Upgrade elliptic to 6.6.1
  yarn.lock
Labels: changesets-ok, release:dependency

#105 chore(test-project): Bump postcss to 8.5.4
  __fixtures__/test-project/web/package.json
Labels: release:chore

#107 chore(deps): Upgrade path-to-regexp to 0.1.12 and to 1.9.0
  docs/yarn.lock
Labels: release:dependency

#109 feat(deps): Upgrade
  .changesets/109.md
  packages/adapters/fastify/web/package.json
  packages/adapters/fastify/web/src/web.test.ts
  packages/adapters/fastify/web/src/webFallback.test.ts
  packages/api-server/package.json
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/createServerHelpers.ts
  packages/web-server/package.json
  yarn.lock
Labels: release:breaking

#110 docs(deploy): Try to deploy the docs to Netlify
  docs/README.md
  docs/netlify.toml
Labels: release:docs

#111 docs(deploy): Increase node memory for Netlify
  docs/docusaurus.config.ts
  docs/netlify.toml
  docs/yarn.lock
Labels: release:docs

#112 chore(docs): CedarJS favicon
  docs/docusaurus.config.ts
  docs/static/img/favicon.ico
Labels: release:docs

#116 chore(deps): Update Docusaurus to v3.8.1
  docs/package.json
  docs/yarn.lock
Labels: release:dependency

#118 feat(docs): llms.txt
  docs/docusaurus.config.ts
  docs/package.json
  docs/yarn.lock
Labels: release:docs

#120 feat(docs): SEO and various config fixes
  docs/docs/create-cedar-app.md
  docs/docs/tutorial/chapter0/what-is-cedarjs.md
  docs/docs/tutorial/foreword.md
  docs/docusaurus.config.ts
  docs/sidebars.js
  docs/src/pages/index.tsx
  docs/static/img/og-image.png
Labels: release:docs

#123 chore(smoke-test): Update default app title
  packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/about.html
  packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/index.html
  packages/adapters/fastify/web/src/__fixtures__/main/web/dist/404.html
  packages/adapters/fastify/web/src/__fixtures__/main/web/dist/about.html
  packages/adapters/fastify/web/src/__fixtures__/main/web/dist/contacts/new.html
  packages/adapters/fastify/web/src/__fixtures__/main/web/dist/index.html
  packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/404.html
  packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/about.html
  packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/contacts/new.html
  packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/index.html
  tasks/server-tests/fixtures/redwood-app/web/dist/404.html
  tasks/server-tests/fixtures/redwood-app/web/dist/about.html
  tasks/server-tests/fixtures/redwood-app/web/dist/contacts/new.html
  tasks/server-tests/fixtures/redwood-app/web/dist/index.html
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
Labels: release:chore

#124 feat(vite): Use Vite for CedarJS's Cell transform
  .eslintrc.js
  packages/babel-config/src/web.ts
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/code.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/output.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/code.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/output.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-export/code.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-export/output.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/code.js
  packages/prerender/src/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/output.js
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-cell.test.ts
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-prerender-media-imports.test.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-cell.ts
  packages/prerender/src/runPrerender.tsx
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/code.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/output.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/code.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/output.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-export/code.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-default-export/output.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/code.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/output.js
  packages/testing/config/jest/babelPlugins/__tests__/__fixtures__/viteDistDir/client-build-manifest.json
  packages/testing/config/jest/babelPlugins/__tests__/babel-plugin-redwood-cell.test.ts
  packages/testing/config/jest/babelPlugins/babel-plugin-redwood-cell.js
  packages/testing/config/jest/web/webBabelConfig.js
  packages/testing/vitest.config.mts
  packages/vite/src/index.ts
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-commented-exports/CodeCell.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-commented-exports/output.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/CodeCell.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/output.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-default-export/CodeCell.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-default-export/output.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-required-exports/CodeCell.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/cell-with-required-exports/output.js
  packages/vite/src/plugins/__tests__/__fixtures__/cell/server-cell-with-data-export/ServerUserCell.jsx
  packages/vite/src/plugins/__tests__/__fixtures__/cell/server-cell-with-data-export/output.js
  packages/vite/src/plugins/__tests__/vite-plugin-cedar-cell.fixtures.test.ts
  packages/vite/src/plugins/__tests__/vite-plugin-cedar-cell.test.ts
  packages/vite/src/plugins/vite-plugin-cedar-cell.ts
Labels: release:feature, changesets-ok

#141 chore(test-project): Update to postcss 8.5.6
  __fixtures__/test-project/web/package.json
Labels: release:chore

#140 fix(jsdoc): currentUser: Update link and remove unusual whitespace
  packages/internal/src/generate/templates/all-currentUser.d.ts.template
Labels: release:fix, changesets-ok

#142 chore(deps): Update `@swc/core` to 1.12.1
  packages/vite/package.json
  yarn.lock
Labels: changesets-ok, release:dependency

#143 chore(deps): Update unplugin-auto-import to 19.3.0
  packages/storybook/package.json
  packages/storybook/src/plugins/auto-imports.ts
  yarn.lock
Labels: changesets-ok, release:dependency

#147 chore(git): Add lefthook
  .prettierignore
  lefthook.yml
  package.json
  yarn.lock
Labels: release:chore

#148 docs(README): Update the migration notes
  README.md
Labels: release:docs

#151 fix(api/cache): use named exports instead of default exports
  .changesets/151.md
  packages/api/src/cache/__tests__/cache.test.ts
  packages/api/src/cache/__tests__/cacheFindMany.test.ts
  packages/api/src/cache/__tests__/deleteCacheKey.test.ts
  packages/api/src/cache/__tests__/disconnect.test.ts
  packages/api/src/cache/clients/BaseClient.ts
  packages/api/src/cache/clients/InMemoryClient.ts
  packages/api/src/cache/clients/MemcachedClient.ts
  packages/api/src/cache/clients/RedisClient.ts
  packages/api/src/cache/index.ts
Labels: fixture-ok, release:fix

#139 feat(prerender): Don't use Babel's require hook
  .eslintrc.js
  packages/prerender/@babel/register.d.ts
  packages/prerender/package.json
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-cell.test.ts
  packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-prerender-media-imports.test.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-cell.ts
  packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
  packages/prerender/src/build-and-import/buildAndImport.ts
  packages/prerender/src/build-and-import/load-tsconfig.d.ts
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/code.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/output.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/code.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-default-and-other-named-export/output.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-default-export/code.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-default-export/output.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/code.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/output.js
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/route-auto-loader/failure/redwood.toml
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/Routes.tsx
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/pages/HomePage/HomePage.tsx
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/pages/HomePage/useHomePage.tsx
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteDistDir/client-build-manifest.json
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteSrcDir/components/Post/Posts/image1.jpg
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteSrcDir/pages/HomePage/funny.gif
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteSrcDir/pages/HomePage/image2.jpeg
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteSrcDir/pages/HomePage/image3.png
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteSrcDir/pages/HomePage/image4.bmp
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteSrcDir/pages/HomePage/small.jpg
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/__fixtures__/viteSrcDir/pdf/invoice.pdf
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/rollup-plugin-cedarjs-prerender-media-imports.test.ts
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/rollup-plugin-cedarjs-routes-auto-loader.test.ts
  packages/prerender/src/build-and-import/rollupPlugins/__tests__/rollup-plugin-ignore-html-and-css-imports.test.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-cell.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-directory-named-imports.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-external.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-ignore-html-and-css-imports.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-inject-file-globals.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-prerender-media-imports.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-routes-auto-loader.ts
  packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-typescript.ts
  packages/prerender/src/build-and-import/rollupPlugins/utils.ts
  packages/prerender/src/build-and-import/types.ts
  packages/prerender/src/build-and-import/utils.ts
  packages/prerender/src/internal.ts
  packages/prerender/src/runPrerender.tsx
  yarn.lock
Labels: release:breaking, changesets-ok

#155 chore(rename): Replace references to "Redwood Blog" with "Cedar Blog"
  __fixtures__/fragment-test-project/web/src/layouts/BlogLayout/BlogLayout.tsx
  __fixtures__/test-project/web/src/layouts/BlogLayout/BlogLayout.tsx
  docs/docs/how-to/pagination.md
  packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/about.html
  packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/index.html
  packages/adapters/fastify/web/src/__fixtures__/main/web/dist/about.html
  packages/adapters/fastify/web/src/__fixtures__/main/web/dist/index.html
  packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/about.html
  packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/index.html
  tasks/e2e/cypress/e2e/01-tutorial/codemods/Step2_1_PagesHome.js
  tasks/e2e/cypress/e2e/01-tutorial/codemods/Step2_2_PagesAbout.js
  tasks/e2e/cypress/e2e/01-tutorial/codemods/Step3_1_LayoutsBlog.js
  tasks/e2e/cypress/e2e/01-tutorial/codemods/Step7_1_BlogLayout.js
  tasks/e2e/cypress/e2e/01-tutorial/sharedTests.js
  tasks/e2e/cypress/e2e/02-cli/02-cli-commands.cy.xs
  tasks/server-tests/fixtures/redwood-app/web/dist/about.html
  tasks/server-tests/fixtures/redwood-app/web/dist/index.html
  tasks/smoke-tests/prerender/tests/prerender.spec.ts
  tasks/smoke-tests/serve/tests/contactUs.spec.ts
  tasks/smoke-tests/shared/common.ts
  tasks/smoke-tests/shared/homePage.ts
  tasks/test-project/codemods/blogLayout.js
Labels: release:chore

#156 fix(corepack): Switch to installing corepack globally from npm
  .github/actions/set-up-job/action.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-release-candidate.yml
  .gitpod.yml
  CONTRIBUTING.md
  docs/docs/docker.md
  docs/docs/how-to/test-in-github-actions.md
  docs/docs/how-to/using-nvm.md
  docs/docs/how-to/using-yarn.md
  docs/docs/tutorial/chapter1/prerequisites.md
  packages/cli/src/commands/setup/deploy/templates/render.js
  packages/cli/src/commands/setup/docker/templates/Dockerfile
  packages/create-cedar-rsc-app/src/prerequisites.ts
Labels: release:fix, changesets-ok

#157 fix(api-server): handle path names with 'graphql'
  packages/api-server/src/__tests__/api.test.ts
  packages/api-server/src/__tests__/createServer.test.ts
  packages/api-server/src/__tests__/fastify.test.ts
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/.env.defaults
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/another-graphql.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/deeplyNested/nestedDir/deeplyNested.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/env.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/graphql.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/health.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/hello.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/nested/nested.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/dist/functions/noHandler.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/api/server.config.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/redwood.toml
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/200.html
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/404.html
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/README.md
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/about.html
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/assets/AboutPage-7ec0f8df.js
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/assets/index-613d397d.css
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/build-manifest.json
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/contacts/new.html
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/favicon.png
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/index.html
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/nested/index.html
  packages/api-server/src/__tests__/fixtures/graphql/cedar-app/web/dist/robots.txt
  packages/api-server/src/__tests__/graphqlPlugin.test.ts
  packages/api-server/src/__tests__/lambdaLoader.test.ts
  packages/api-server/src/plugins/lambdaLoader.ts
Labels: release:fix, changesets-ok

#158 fix(supertokens): Fix whitespace handling in setup script
  packages/auth-providers/supertokens/setup/src/__tests__/setupHandler.test.ts
  packages/auth-providers/supertokens/setup/src/setupHandler.ts
Labels: release:fix, changesets-ok

#161 chore(clean-build): script to reset everything to a clean slate
  package.json
  tasks/git-clean-build.mjs
Labels: release:chore
